---
title: "QIIME2_Visualization"
author: "Dave Hein"
date: "1/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r}
data_for_abundance2 <- read.delim("C:/Users/s197002/OneDrive - University of Texas Southwestern/poop/First Round Poo Data/QIIME2/data_for_abundance_2.txt")


df<- data_for_abundance%>%rename("Other Actinobacteria Families"="Other.Actinobacteria",
                                 "Other Bacteroidetes Families"= "Other.Bacteroidetes",
                                 "Other Non-Clostridial Firmicute Families"="Other.Non.Clostridial.Firmicutes",
                                 "Other Clostridial Firmicute Families"="Other.Clostridia",
                                 "Other Bacteria"="Other.Bacteria")%>%
                          pivot_longer(cols = c("Bifidobacteriaceae",
                                                "Other Actinobacteria Families",
                                                "Bacteroidaceae","Prevotellaceae",
                                                "Other Bacteroidetes Families",
                                                "Enterococcaceae",
                                                "Lactobacillaceae",
                                                "Other Non-Clostridial Firmicute Families",
                                                "Ruminococcaceae",
                                                "Eubacteriaceae",
                                                "Lachnospiraceae",
                                                "Peptostreptococcaceae",
                                                "Other Clostridial Firmicute Families",
                                                "Fusobacteriaceae",
                                                "Enterobacteriaceae",
                                                "Other Bacteria","Archea"))%>% 
                          rename(Bacteria_Family=name,Relative_Abundance=value)%>%
                          mutate(Bacteria_Family=as.factor(Bacteria_Family))

df$Bacteria_Family<-factor(df$Bacteria_Family,levels=c(

                                                
                                                "Archea",
                                                
                                                "Other Bacteria",
                                                
                                                
                                                
                                                "Fusobacteriaceae",
                                                
                                                "Enterobacteriaceae",
                                                
                                                "Other Actinobacteria Families",
                                                "Bifidobacteriaceae",
                                                
                                                
                                                "Other Bacteroidetes Families",
                                                "Bacteroidaceae",
                                                "Prevotellaceae",
                                                
                                                
                                                "Other Non-Clostridial Firmicute Families",
                                                "Enterococcaceae",
                                                "Lactobacillaceae",
                                                
                                                
                                                "Other Clostridial Firmicute Families",
                                                "Eubacteriaceae",
                                                "Ruminococcaceae",
                                                "Peptostreptococcaceae",
                                                "Lachnospiraceae"
                                                
                                                ))


df$ID<-factor(df$ID,levels=c("San1","San2","San4","San9","San3","San5","San6","San7","San11","San12","San14"))
                                        




ggplot(df, aes(fill=Bacteria_Family, y=Relative_Abundance, x=ID)) + 
    geom_bar(position="fill", stat="identity",width=0.6)+
    #theme(axis.text.x = element_text(angle = 90,vjust=.35))+
    scale_fill_manual(values=c(
                                
                                #3 class yellow green blue ^
                              "Bifidobacteriaceae" = "#3182bd",
                               "Other Actinobacteria Families" = "#9ecae1",
                              
                               #4 hue 50  yellos
                              "Other Bacteroidetes Families" = "#ffee99",
                               "Bacteroidaceae" = "#ffd500",
                               "Prevotellaceae" = "#ccaa00",
                               
                               
                              #4 class pur^
                              "Other Non-Clostridial Firmicute Families" = "#cbc9e2",
                              "Enterococcaceae" = "#9e9ac8",
                              "Lactobacillaceae"="#6a51a3",
                              
                              
                               #6 class green ^
                              "Other Clostridial Firmicute Families" = "#c7e9c0",
                              "Eubacteriaceae" = "#a1d99b",
                              "Ruminococcaceae" = "#74c476",
                              "Peptostreptococcaceae" = "#31a354",
                              "Lachnospiraceae" = "#006d2c",
                               
                              #3 class greys middle
                               "Fusobacteriaceae" = "#bdbdbd",
                               
                              #3 class red middle
                               "Enterobacteriaceae" = "#fc9272",
                               
                              #3class orange middle
                               "Other Bacteria" = "#fdae6b",
                               
                              #3 class greys darkest
                               "Archea" = "#636363"))+
  xlab("Patient ID")+
  ylab("Relative Abundance")+
  theme_classic()+
  ggtitle("Bacterial Family Composition")
  

    


ggsave(plot=last_plot(), height = 6, width = 10,filename = "fig.png")


#Actinobacteria: dark blue
#Bacteroidetes: yellow
#Non-clostridial Firmicutes: maroon
#Clostridial Firmicutes: green
#Proteobacteria: red
#Other: orange
```


```{r}

df<- data_for_abundance2%>%rename("Other Actinobacteria Families"="Other.Actinobacteria",
                                 "Other Bacteroidetes Families"= "Other.Bacteroidetes",
                                 "Other Non-Clostridial Firmicute Families"="Other.Non.Clostridial.Firmicutes",
                                 "Other Clostridial Firmicute Families"="Other.Clostridia",
                                 "Other Bacteria"="Other.Bacteria")%>%
                          pivot_longer(cols = c("Bifidobacteriaceae",
                                                "Other Actinobacteria Families",
                                                "Bacteroidaceae",
                                                "Prevotellaceae",
                                                "Other Bacteroidetes Families",
                                                
                                                
                                                "Other Non-Clostridial Firmicute Families",
                                                "Ruminococcaceae",
                                                
                                                "Lachnospiraceae",
                                                "Peptostreptococcaceae",
                                                "Other Clostridial Firmicute Families",
                                                "Fusobacteriaceae",
                                                
                                                "Other Bacteria"))%>% 
                          rename(Bacteria_Family=name,Relative_Abundance=value)%>%
                          mutate(Bacteria_Family=as.factor(Bacteria_Family))



df$Bacteria_Family<-factor(df$Bacteria_Family,levels=c(

                                                
                                                
                                                
                                                
                                            
                                                
                                                
                                                "Bifidobacteriaceae",
                                                "Other Actinobacteria Families",
                                                
                                                "Prevotellaceae",
                                                "Bacteroidaceae",
                                                "Other Bacteroidetes Families",
                                                
                                                "Other Non-Clostridial Firmicute Families",

                                                "Lachnospiraceae",
                                                "Ruminococcaceae",
                                                "Peptostreptococcaceae",
                                                "Other Clostridial Firmicute Families",
                                          
                                                "Fusobacteriaceae",
                                                
                                                "Other Bacteria"
                                                ))


df$ID<-factor(df$ID,levels=c("P1","P2","P4","P9","P3","P5","P6","P7","P11","P12","P14"))


ggplot(df, aes(fill=Bacteria_Family, y=Relative_Abundance, x=ID)) + 
    geom_bar(position="fill", stat="identity",width=0.6)+
    #theme(axis.text.x = element_text(angle = 90,vjust=.35))+
    scale_fill_manual(values=c(
                                
                                #yellow
                               "Other Actinobacteria Families" = "#FFE500",
                              "Bifidobacteriaceae" = "#DBC500",
                               
                              
                               #Green
                              "Other Bacteroidetes Families" = "#82c273",
                               "Bacteroidaceae" = "#4a883f",
                               "Prevotellaceae" = "#0d520d",
                               
                              #Light blue 
                              "Other Non-Clostridial Firmicute Families" = "#A2B5FF",

                               #Magenta 
                              "Other Clostridial Firmicute Families" = "#ffcfff",
                              "Ruminococcaceae" = "#a76a92",
                              "Peptostreptococcaceae" = "#d39bc7",
                              "Lachnospiraceae" = "#520a30",
                               
                              #Dark Blue
                               "Fusobacteriaceae" = "#102f6b",
                               
                              #orange
                               "Other Bacteria" = "#FF9C70"))+
  xlab("Patient ID")+
  ylab("Relative Abundance")+
  theme_classic()+
  ggtitle("Bacterial Family Composition")+
  theme(text=element_text(family="Times New Roman") )

ggsave(plot=last_plot(), height = 6, width = 10,filename = "fig.png")




```



```{r}

lefse_values_graph <- read.delim("C:/Users/s197002/OneDrive - University of Texas Southwestern/poop/First Round Poo Data/QIIME2/lefse_graph_values.txt")

lefse <- lefse_values_graph%>%mutate(taxon=as.factor(taxon),group=as.factor(group))%>%rename(Response=group)

ggplot(lefse, aes(fill=Response, y=LDA, x=reorder(taxon,LDA))) + 
    geom_bar(stat="identity")+coord_flip()+xlab("")+ylab("LDA SCORE (log 10)")+
    scale_fill_manual(values=c("Complete/Near Complete" = "#27CDDB","Partial" = "#A268D1")) +
  scale_y_continuous(breaks=c(-4.8,-3.6,-2.4,-1.2,0.0,1.2,2.4,3.6,4.8))+theme_bw()+ 
  
  theme(text=element_text(family="Times New Roman"),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  
  geom_text(aes(label=taxon2),family="Times New Roman",hjust="inward",y=.05)+
  geom_text(aes(label=taxon3),family="Times New Roman",hjust="outward",y=-.05)+
  theme(legend.position="bottom")


ggsave(plot=last_plot(), height = 4, width = 6,filename = "fig2.png")

```










